### ISSUE TITLE
Improve formatting for very long threads

### ISSUE THREAD

**Issue by steren** [tweetback/tweetback#9]
I maintain an extremely long Twitter thread (https://twitter.com/steren/status/1586136999836078081)

tweetback renders threads like email threads, where each response adds one indentation. 

As a consequence, this long thread looks like this: http://twitter.steren.fr/1586136999836078081/

![image](https://user-images.githubusercontent.com/360895/203243689-e5a7a2f0-bd6d-457d-9960-c6297f5acdd6.png)

**Comment by nhoizey** [comment]
Whoops, not great indeed! 😅

I guess we should stop indentation after some depth level, maybe 10?

Or maybe remove all indentation, finding a better visual hint for threads?

**Comment by Accudio** [comment]
A CSS addition to limit indentation at a depth of 10 would be relatively straightforward (if ugly):

```css
.tweets .tweets-replies > * > * > * > * > * > * > * > * > * > * {
    border-left: 0;
    padding-left: 0;
    margin-left: 0;
}
```

Trying it out on @steren's site however looks a little odd, having a visual hint of threads that is meaningless for > 10. Perhaps a different or additional visual hint would be useful in that case.
